backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads" # Folder the public can access
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
